  language: python
  python:
    - "3.8"

  services:
    - docker

  before_install:
    - echo 'bar'

  script:
    - echo 'foo'

  deploy:
    provider: heroku
    api_key: $HEROKU_TOKEN
    app : square-master-test
    skip_cleanup: True
  
  # language: python
  
  # services:
  #   - docker
  
  # before_install:
  #   - echo 'test'
  #   - wget -q0- https://toolbelt.heroku.com/install.sh | sh 
  #   - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

  # script:
  #   - docker tag sboomi/square-master-test registry.heroku.com/$HEROKU_APP_NAME/web

  # deploy:
  #   provider: script
  #   script: 
  #     heroku container:push web --app $HEROKU_APP_NAME 
  #     heroku container:release web --app $HEROKU_APP_NAME
  #   on:
  #     branch: master